language: php

php:
 - 7.1

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --no-interaction

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
 - vendor/bin/phpstan analyse -l 7 src/

after_script:
 - php vendor/bin/coveralls -v
